### ISSUE TITLE
Please trigger a setState() to activate Lucid devtool.

### ISSUE THREAD

**Issue by FredyC** [Gossamer-React/Lucid#137]
**Describe the bug**
I am not sure what is meant by this error message. I do have React devtools installed and working just fine.

**To Reproduce**
Hard to know, I suppose it's some environment issue since no one else is reporting it.

The app is running React 16.7.0-alpha.2 in development mode. There is react-apollo 2.2.4.

I don't use Redux, so if the `setState` is somehow related to that, it should be mentioned somewhere.

**Expected behavior**
It should show the promised wow UI :)

**Screenshots**
![image](https://user-images.githubusercontent.com/1096340/51053584-5aaf4300-15da-11e9-9e20-457dbf2a297d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 
 - Browser chrome
 - Version 71

**Comment by FredyC** [comment]
@neyser95 Well, yea, it's not clear :) What state? I basically tried to navigate within the app, there is react-router. Changing URL alone should be considered as a change of state. Bunch of GraphQL queries was also executed. That's the main reason I want to try the tool, to inspect GraphQL.

**Comment by neyser95** [comment]
@FredyC I see alright we'll take a look at this and run some more tests. It may have to do with React 16.7.0-alpha.2, but we'll update this as soon as we figure it out. Thank you.

**Comment by tnrich** [comment]
I'm also stuck on the above screen and have react devtools installed and am using react 16+. That said, this is an app that doesn't actually have any graphql layer, but it seems like the lucid devtool should still work? I have triggered setState's within my app.

![image](https://user-images.githubusercontent.com/2730609/51097639-689bca00-177a-11e9-970e-5220660c90cf.png)

**Comment by tnrich** [comment]
Perhaps mine is coming from a different issue.
I'm getting: 
```
Error in event handler for (unknown): TypeError: Cannot read property 'trace' of undefined
```
in the console: 

![image](https://user-images.githubusercontent.com/2730609/51100812-a0137200-178c-11e9-87d0-55a6033a6cb0.png)

**Comment by tgreen7** [comment]
I am seeing the same page on our app which is React 16+ and is using graphql. But I have a different error.
```Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at setTimeout (reactTraverser.js:30)```

**Comment by FredyC** [comment]
@tgreen7 Yea, I was seeing same error and thought at first it's happening in my app, only after removing Lucid, the culprit was clear :)

**Comment by eternalee** [comment]
Hi,

I wanted to add $.02 to the two issues mentioned!
**Trigger setState -** 
We're relying on Facebook React DevTool's ReactGlobalHook function to re-traverse the DOM and it is usually invoked whenever setState is invoked/re-render happens at a component level. If a user only navigates around the app with react-router, there is a possibility it's not triggering the traverse functionality.

**Converting circular structure to JSON**
This is a known issue on the top of our backlog! We're still looking into solutions and welcome feedback. I _think_ the bug is because we traverse the DOM to create a large nested object (representing that DOM) and then JSON._stringify_ that object to send it into our app's react-D3-tree graph. There are references between dom parent-child and child-parent (i.e. a child points to its parent which has a list of its children), but JSON doesn't support references, hence the console error.

**Comment by neyser95** [comment]
@tnrich Hi, apart from the other issue mention which seems to be the circular structure to JSON. Your issue is one that we have not seen. Could you please provide what steps you may have taken to get this error? We want to make sure that we cover as many edge cases as we can. Thank you.

**Comment by pitops** [comment]
Hey guys, kudos for the plugin but unfortunately I can't test it either.

I get the same setState screen and also the Circular issue. Usually this type of circular dependency is because of JSON.stringify you mentioned. Maybe on of the solutions [here](https://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json) work for you

Circular reference snippet

```javascript
Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at setTimeout (reactTraverser.js:30)
```

I am using NextJS with React 16.7, Apollo Client and Graphql-yoga(which includes Apollo server) on backend

**Comment by neyser95** [comment]
@pitops Thank you for the resource. It looks promising, we should be able to create a custom replacer for devtool use. Well let everyone know when we have an update on this issue.

**Comment by HeadFox** [comment]
@pitops What did you add to fix this issue ?

**Comment by neyser95** [comment]
@pitops Hi is there any chance that the repo you are using is public?? I would like to use it to test the 'Converting circular structure to JSON' error. Thank you.

**Comment by neyser95** [comment]
@HeadFox Hi could you let me know if you're using Apollo? I you are please let me know what version. If you are not using Apollo then please know that right now Lucid only works with Apollo servers and that we are working to make sure that it can support more than just Apollo GraphQL servers. Thank you.

**Comment by HeadFox** [comment]
@neyser95 Here, you can see my dependencies
```
"dependencies": {
    "apollo-boost": "^0.1.27",
    "express": "^4.16.4",
    "graphql": "^14.1.1",
    "graphql-tag": "^2.10.1",
    "next": "^7.0.2",
    "next-with-apollo": "^3.3.2",
    "prop-types": "^15.6.2",
    "react": "^16.6.1",
    "react-apollo": "^2.4.0",
    "react-dom": "^16.6.1",
    "react-jss": "^8.6.1",
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "babel-core": "^7.0.0-0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "babel-plugin-module-resolver": "^3.1.3",
    "enzyme": "^3.7.0",
    "eslint": "^5.12.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.15.0",
    "eslint-plugin-jest": "^22.0.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.12.4",
    "jest": "^23.6.0",
  }
```

**Comment by pitops** [comment]
@neyser95 Unfortunately, I cannot provide access to my repo...

**Comment by neyser95** [comment]
Hey everyone, I just merged a few changes. These new changes should be able to get rid of the circular JSON error while still keeping information about properties of a component. If you want the changes right away then you can manually add Lucid to your browser or wait for the changes to be push to the chrome store but it takes some time to get it reviewed. Please give it a try and let me know if anyone still gets this error. Thank you.

**Comment by HeadFox** [comment]
It works now :) !! No more error ! Thanks @neyser95 
I will now try the extensions, it looks really promising ! :)
